server:
  port: 8091
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///offcnpe
    username: root
    password: root
  application:
    name: manage_provider

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  mapper-locations: classpath:/mapper/xml/*.xml
  type-aliases-package: com.generate.pojo

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://10.10.33.200:2181
    timeout: 100000
  scan:
    base-packages: com.generate.impl

